name: Auto-merge PRs

on:
  pull_request:
    types: [closed, opened, reopened, synchronize]

jobs:
  automerge:
    # if a PR is from this repository (not a fork), enable automerge
    if: github.event.pull_request.action != 'closed' && github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Enable automerge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr merge --auto --squash "$PR_URL"
        shell: bash

  # automatic branch deletion on merge doesn't appear to work when a PR is auto-merged
  # so this job does that explicitly
  delete-branch:
    if: github.event.pull_request.action == 'closed' && github.event.pull_request.merged && github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      # checkout the PR source branch so we can delete it after merge
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Delete PR branch
        run: |
          git push -d origin "${{ github.event.pull_request.head.ref }}"
        shell: bash